import * as React from "react";
import Container from "react-bootstrap/Container";
import { PropertyInterface } from "../Property/Property";
import { LandlordInterface } from "./Landlord";

export interface LandlordsInterface {
  landlords: LandlordInterface[]
}

export default function Landlords() {
  return (
    <Container>
      <h3>Landlords</h3>
      <br />
      <h5>
        A React component, inside another React component, supported by a Rails
        API
      </h5>
      <br />
      <p>
        A list of all of the landlords in our database will be generated by this
        absolutely stunning component.
      </p>
      <br />
    </Container>
  );
}
