import * as React from "react";
import Container from "react-bootstrap/Container";
import { LandlordInterface } from "./Landlord";
import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

export type Landlords = {
  landlords: LandlordInterface[];
};

export default function Landlords() {
  return (
    <Container>
      <h3>Landlords</h3>
      <br />
      <h5>
        A React component, inside another React component, supported by a Rails
        API
      </h5>
      <br />
      <p>
        A list of all of the landlords in our database will be generated by this
        absolutely component.
      </p>
      <br />
      <Form>
        <Form.Group className="mb-3" controlId="searchInput">
          <Form.Label>Search for Landlord by Name</Form.Label>
          <Form.Control type="text" placeholder="Search" />
          <Form.Text className="text-muted">
            Search for a landlord by name.
          </Form.Text>
        </Form.Group>
        <Button variant="primary" type="submit">
          Search
        </Button>
      </Form>
    </Container>
  );
}
